<?php
// START SESSION TO ACCESS SESSION VARIABLES
session_start();

// CHECK IF USER IS LOGGED IN BY VERIFYING IF USERID EXISTS IN SESSION
// RETURN '1' IF LOGGED IN, '0' IF NOT LOGGED IN
// THIS IS USED FOR AJAX CALLS TO DETERMINE USER LOGIN STATUS
echo isset($_SESSION['UserID']) ? '1' : '0';
?>